# Generated by Django 3.2 on 2021-04-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myemotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Angry_count', models.IntegerField()),
                ('Happy_count', models.IntegerField()),
                ('Neutral_count', models.IntegerField()),
                ('Sad_count', models.IntegerField()),
                ('Surprise_count', models.IntegerField()),
                ('Final_text', models.CharField(max_length=100)),
            ],
        ),
    ]
